version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8501:8501"
    networks:
      - app-network
  
  svm_service:
    build:
      context: .
      dockerfile: ./svm_service/Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network

  vgg19_service:
    build:
      context: .
      dockerfile: ./vgg_service/Dockerfile
    ports:
      - "5001:5001"
    networks:
      - app-network

   
volumes:
  jenkins_home:
