version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./tests:/app/tests 
    ports:
      - "8501:8501"
  
  svm_service:
    build:
      context: ./svm_service
    volumes:
      - ./svm_service:/app/svm_service
      - ./tests:/app/tests 
    ports:
      - "5000:5000"

  vgg19_service:
    build:
      context: ./vgg_service
    volumes:
      - ./vgg_service:/app/vgg_service
      - ./tests:/app/tests 
    ports:
      - "5001:5001"
networks:
  app-network:
    driver: bridge
volumes:
  jenkins_home:
