version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
  
  svm_service:
    build:
      context: ./svm_service
    volumes:
      - ./svm_service:/app/svm_service
    ports:
      - "5000:5000"

  vgg19_service:
    build:
      context: ./vgg_service
    volumes:
      - ./vgg_service:/app/vgg_service
    ports:
      - "5001:5001"

  jenkins-project:
    build:
      context: .
    container_name: jenkins-project
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock 
      - /usr/local/bin/docker:/usr/local/bin/docker
    environment:
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
    user: root
    networks:
      - app-network

volumes:
  jenkins_home:

networks:
  app-network:
    driver: bridge
